# Generated by Django 6.0.1 on 2026-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User")],
                default="USER",
                max_length=20,
            ),
        ),
    ]
