# Generated by Django 6.0.1 on 2026-03-23 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_auth_provider_user_google_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auth_provider",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("email", "Email"), ("google", "Google")], max_length=20
                    ),
                ),
                ("provider_id", models.CharField(db_index=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "provider_id")},
            },
        ),
    ]
