# Generated by Django 6.0.1 on 2026-03-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_auth_provider_remove_user_google_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialAccount",
        ),
    ]
