# Generated by Django 6.0.1 on 2026-01-30 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
        ),
        migrations.AddField(
            model_name='questioncontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.content'),
        ),
        migrations.AddField(
            model_name='questioncontent',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='questions.question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_user_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questioncontent',
            constraint=models.UniqueConstraint(fields=('question', 'content'), name='unique_question_content'),
        ),
    ]
