# Generated by Django 6.0.1 on 2026-03-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='start_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
