# Generated by Django 6.0.1 on 2026-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='allowed_answer_types',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='questions.content'),
        ),
    ]
