# Generated by Django 6.0.1 on 2026-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_end_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
